name: "publish"
on:
  push:
    branches:
      - main
jobs:
  publish-package:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - uses: manoadamro/rust-release@v1
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.repository }}
        token: ${{ secrets.TOKEN }}
